export const AUTHENTICATED = "AUTHENTICATED";
export const UNAUTHENTICATED = "UNAUTHENTICATED";
export const SIGNED_UP = "SIGNED_UP";

export const GET_COURSES = 'GET_COURSES';
export const CREATE_COURSE = 'CREATE_COURSE';
export const SEARCH_COURSE = 'SEARCH_COURSE';
export const ENROLL_COURSE = 'ENROLL_COURSE';
export const WAITLIST_COURSE = 'WAITLIST_COURSE';
export const DROP_COURSE = 'DROP_COURSE';
export const COURSE_DETAILS = 'COURSE_DETAILS';
export const GET_COURSE_BY_ID = 'GET_COURSE_BY_ID';

export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const ASSIGNMENT_DETAILS = 'ASSIGNMENT_DETAILS';
export const GET_ASSIGNMENT_BY_ID = 'GET_ASSIGNMENT_BY_ID';
export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT';
export const SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT';
export const FIND_USERS_WITH_ASSIGNMENT = 'FIND_USERS_WITH_ASSIGNMENT';
export const GET_ASSIGNMENTS_BY_USER_COURSE_ASSIGNMENT_IDS = 'GET_ASSIGNMENTS_BY_USER_COURSE_ASSIGNMENT_IDS';
export const SELECTED_USER_FOR_ASSIGNMENT_GRADING = 'SELECTED_USER_FOR_ASSIGNMENT_GRADING';
export const GRADE_ASSIGNMENT = 'GRADE_ASSIGNMENT';
export const GET_ASSIGNMENT_FOR_GRADE = 'GET_ASSIGNMENT_FOR_GRADE';

export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const ANNOUNCEMENT_DETAILS = 'ANNOUNCEMENT_DETAILS';
export const GET_ANNOUNCEMENT_BY_ID = 'GET_ANNOUNCEMENT_BY_ID';
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT';

export const GET_PROFILE = 'GET_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';

export const GET_USER = 'GET_USER';

export const GET_QUIZ_BY_ID = 'GET_QUIZ_BY_ID';
export const CREATE_QUIZ = 'CREATE_QUIZ';

export const GET_FILES_BY_COURSE_ID = 'GET_FILES_BY_COURSE_ID';
export const UPLOAD_FILES_BY_COURSE_ID = 'UPLOAD_FILES_BY_COURSE_ID';

export const GET_PEOPLE_BY_COURSE_ID = 'GET_PEOPLE_BY_COURSE_ID';